### ISSUE TITLE
What do you mean exactly by the term TEST MODE?

### ISSUE THREAD

**Issue by AntiiHeld** [lyc8503/Sandboxie-crack#1]
### Describe what you noticed and did

Hello, I am currently setting up Sandboxie and would like to use your patched version. What exactly do you mean by the TEST MODE needing to be activated? How can I activate it? I have already checked in the settings but found nothing. I would greatly appreciate your help. Thank you very much.

### Affected program

Not relevant

### Download link

Not Available

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Hello, I am currently setting up Sandboxie and would like to use your patched version. What exactly do you mean by the TEST MODE needing to be activated? How can I activate it? I have already checked in the settings but found nothing. I would greatly appreciate your help. Thank you very much.

### What is your Windows edition and version?

Windows 10

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

The Version you upload on Github

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by teknixstuff** [comment]
You have to enable Windows Driver Test Mode.
To do so, right-click your start button, select `Command Prompt (admin)`, click yes, type `bcdedit -set TESTSIGNING ON`, press enter, and then restart your computer. If it worked, you should see the words `Test Mode` in the bottom-right of your desktop.

**Comment by sthalik** [comment]
Is there a way to avoid running in test mode for an indefinite period of time, such as by adding in one of your certificates?

**Comment by shiryzz** [comment]
test mode didnt work for me

**Comment by shiryzz** [comment]
https://www.4shared.com/s/faBlm-_QZge

that patch works, but some anti virus found trojan
could someone fix it?

**Comment by lyc8503** [comment]
Hi, I've added a link to Microsoft explaining how to enable `TEST MODE`, please refer to that.

Signing using a leaked certificate usually causes false positives in anti virus, that's not avoidable.

> that patch works, but some anti virus found trojan
