### ISSUE TITLE
What version of Sandboxie is this equivalent to?

### ISSUE THREAD

**Issue by Darthagnon** [lyc8503/Sandboxie-crack#2]
### Describe what you noticed and did

I noticed that this fork of Sandboxie has binaries listed as:
- 1.9.6
- 20 Jan 2024

This is incongruous, as [Sandboxie v1.9.6](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.6) is from 30 May 2023, and the release prior to 20 Jan 2024 is [Sandboxie v1.12.7](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.12.7). I tried comparing the Git log, but that didn't make sense, either, as it deviates on 4 Dec 2023 (around [Sandboxie v1.12.3](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.12.3))

So what version is this fork equivalent to? Is it up-to-date with official Sandboxie releases?

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

The version number and date should match official Sandboxie releases.

### What is your Windows edition and version?

Windows 10 Home 1709

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie 1.13

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by Darthagnon** [comment]
And the binary `SandMan.exe` has `v1.9.7` in its properties. Very confusing.

**Comment by lyc8503** [comment]
Hello, this Sandboxie version is equivalent to the official v1.9.6 version, I tried upgrading it before, but after it failed I rolled it back, so maybe the release time is not consistent with the upstream.

**Comment by lyc8503** [comment]
I've just synced with upstream, and now the latest version is v1.14.7
