### ISSUE TITLE
开了TEST模式禁用了驱动签名后无法玩EAC游戏

### ISSUE THREAD

**Issue by Molarczsq** [lyc8503/Sandboxie-crack#4]
### Describe what you noticed and did

有什么解决办法吗，sys签名，相关证书能提供吗

### Expected behavior

Driver sign

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Not relevant

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

10 22h2

### In which Windows account you have this problem?

A Microsoft account (Standard user).

### Please mention any installed security software

Not relevant

**Comment by FlysoftBeta** [comment]
https://github.com/TheCruZ/kdmapper

**Comment by lyc8503** [comment]
可以在 #5 这里讨论
